name: prod-pipeline-with-steps

pool: 
  vmImage: 'ubuntu-latest'

trigger: none
steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
  - task: CmdLine@2
    inputs:
      script: |
        echo Write your commands here
        
        my name is Tiger
