name: Pipeline with job
pool:
  vmImage: ubuntu-latest
trigger: none
jobs:
  - job: codescan
    steps:
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
  - job: Terraform
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'prod-connection'
        backendAzureRmResourceGroupName: 'rgbydeepak'
        backendAzureRmStorageAccountName: 'prodstorageind'
        backendAzureRmContainerName: 'remote'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Basic/'
        environmentServiceNameAzureRM: 'prod-connection'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Basic/'
        environmentServiceNameAzureRM: 'prod-connection'